name: odmltables
dependencies:
  - python ==3.11
  - zlib
  - libgcc-ng
  - ncurses
  - libuuid
  - sqlite
  - xz
  - setuptools
  - snowballstemmer
  - sphinx
  - sphinx_rtd_theme
  - pip
  - pip:
    - odml
